import {type NextPage} from "next";
import Head from "next/head";

import {useEffect, useState} from "react";
import {trpc} from "../utils/trpc";
import GQL from "../utils/graphql";
import ProductCard from "../components/ProductCard/ProductCard";

const Home: NextPage = () => {
//  const hello = trpc.shopify.collection.useQuery({ text: "from tRPC" });

    const [products, setProducts] = useState([]);

    useEffect(() => {
       GQL().then((response) => {
           response.json().then(({ data }) => {
            setProducts(data?.products?.edges);
           });
       });
    }, []);

    console.log(products);
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
              {
                  products && products.map(({node}) => <ProductCard {...node} />)
              }
            </main>
        </>
    );
};

export default Home;

type TechnologyCardProps = {
    name: string;
    description: string;
    documentation: string;
};